# config file version
apiVersion: 1

# list of datasources to insert/update depending
# whats available in the database
datasources:
  - name: influx
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    database: telegraf
    editable: true
